# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181229_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
