# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181230_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_message_read',
            field=models.BooleanField(default=False),
        ),
    ]
